import Head from "next/head"
import { NotificationProvider } from "web3uikit"
import { MoralisProvider } from "react-moralis"
import Header from "../components/Header"
import "../styles/globals.css"
const MORALIS_SERVER_URL = process.env.NEXT_PUBLIC_MORALIS_SERVER_URL
const MORALIS_APP_ID = process.env.NEXT_PUBLIC_MORALIS_APP_ID

function MyApp({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title>NFT Marketplace</title>{" "}
                <meta name="" content="Generated by create next app" />{" "}
                <link rel="icon" href="/favicon.ico" />{" "}
            </Head>

            <MoralisProvider serverUrl={MORALIS_SERVER_URL} appId={MORALIS_APP_ID}>
                <NotificationProvider>
                    <Header />
                    <Component {...pageProps} />
                </NotificationProvider>
            </MoralisProvider>
        </div>
    )
}

export default MyApp
